name: Seabrick subgraph CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Extract version from package.json
        id: extract_version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Print version
        run: echo "Version is $VERSION"

      - name: Codegen
        run: npm run codegen

      - name: Build
        run: npm run build
